services:
    employee-self-service.mariadb:
        image: 'docker.arvancloud.ir/mariadb:10'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sail-mariadb:/var/lib/mysql'
            - ./mydb.cnf:/etc/mysql/conf.d/my.cnf
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    employee-self-service.phpmyadmin: 
        image: 'docker.arvancloud.ir/phpmyadmin'
        restart: always 
        environment: 
            PMA_HOST: employee-self-service.mariadb 
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            UPLOAD_LIMIT: 100M 
        ports: 
            - ${FORWARD_PMA_PORT:-9080}:80 
        networks: 
            - sail 
        depends_on: 
            - employee-self-service.mariadb
networks:
    sail:
        driver: bridge
volumes:
    sail-mariadb:
        driver: local
